/**
 * Portfolio Compute — deterministic asset allocation.
 *
 * All numbers produced here are computed, not generated by an LLM.
 * The LLM is only used for the rationale narrative after these values are known.
 *
 * Rules:
 *   1. Base allocation by risk_tolerance (low / medium / high)
 *   2. Glide-path shift toward bonds as retirement approaches (≤10 and ≤5 years)
 *   3. Expected annual return = weighted blend: equities@9%, bonds@3%
 *   4. Rebalance frequency: quarterly when ≤5 yrs to retirement, annually otherwise
 */

const BASE_ALLOCATIONS = {
  low:    { Equities: 30, Bonds: 55, 'Real Estate': 5, Cash: 10 },
  medium: { Equities: 60, Bonds: 30, 'Real Estate': 5, Cash:  5 },
  high:   { Equities: 80, Bonds: 12, 'Real Estate': 5, Cash:  3 },
};

const EQUITY_RETURN = 0.09; // long-run equity return estimate
const BOND_RETURN   = 0.03; // conservative bond return

/**
 * Compute deterministic portfolio allocation.
 *
 * @param {object} profile     { age, retirement_age, risk_tolerance }
 * @param {object} simulation  { savings_gap, can_retire_at_target }
 * @returns {object}           allocation, strategy, expected_annual_return_percent,
 *                             rebalance_frequency, _inputs
 */
export function computePortfolioAllocation(profile = {}, simulation = {}) {
  const riskTolerance    = (profile?.risk_tolerance || 'medium').toLowerCase();
  const age              = Number(profile?.age)            || 35;
  const retirementAge    = Number(profile?.retirement_age) || 65;
  const yearsToRetirement = Math.max(0, retirementAge - age);

  // ── 1. Base allocation ────────────────────────────────────────────────────
  const base = { ...(BASE_ALLOCATIONS[riskTolerance] ?? BASE_ALLOCATIONS.medium) };

  let equities   = base.Equities;
  let bonds      = base.Bonds;
  let realEstate = base['Real Estate'];
  let cash       = base.Cash;

  // ── 2. Glide-path: tilt bonds as retirement nears ─────────────────────────
  let glidePath = 'accumulation';
  if (yearsToRetirement <= 5) {
    equities   = Math.max(20, equities - 20);
    bonds      = Math.min(65, bonds + 18);
    cash       = Math.min(15, cash + 2);
    realEstate = 100 - equities - bonds - cash;
    glidePath  = 'near-retirement';
  } else if (yearsToRetirement <= 10) {
    equities   = Math.max(30, equities - 10);
    bonds      = Math.min(60, bonds + 9);
    realEstate = 100 - equities - bonds - cash;
    glidePath  = 'mid-glide';
  }

  // ── 3. Normalise to exactly 100 ───────────────────────────────────────────
  const total = equities + bonds + realEstate + cash;
  if (total !== 100) cash = Math.max(0, cash + (100 - total));

  const allocation = [
    { asset: 'Equities',    percent: equities   },
    { asset: 'Bonds',       percent: bonds      },
    { asset: 'Real Estate', percent: realEstate },
    { asset: 'Cash',        percent: cash       },
  ];

  // ── 4. Expected annual return: weighted blend ─────────────────────────────
  const equityFraction  = equities / 100;
  const expectedReturn  = Math.round(
    (equityFraction * EQUITY_RETURN + (1 - equityFraction) * BOND_RETURN) * 1000,
  ) / 10; // one decimal place, e.g. 6.6

  // ── 5. Strategy label ─────────────────────────────────────────────────────
  const strategy = equities >= 70 ? 'aggressive'
                 : equities >= 50 ? 'balanced'
                 : equities >= 30 ? 'conservative'
                 : 'very_conservative';

  // ── 6. Rebalance frequency ────────────────────────────────────────────────
  const rebalanceFrequency = yearsToRetirement <= 5 ? 'quarterly' : 'annually';

  return {
    allocation,
    strategy,
    expected_annual_return_percent: expectedReturn,
    rebalance_frequency: rebalanceFrequency,
    // Inputs exposed so the LLM can reference them in rationale text
    _inputs: {
      riskTolerance,
      yearsToRetirement,
      equityPercent: equities,
      glidePath,
    },
  };
}
