/**
 * Risk Compute — deterministic risk scoring and stress tests.
 *
 * All numbers produced here are computed, not generated by an LLM.
 * The LLM is only used for factor descriptions and mitigation steps (narrative).
 *
 * Scoring factors (each 0–3 points):
 *   • Equity concentration  — higher equity % → higher risk
 *   • Time horizon          — closer to retirement → higher risk
 *   • Savings gap           — larger gap → higher risk
 *
 * Overall score (1–10) = weighted average across the three factors.
 * Stress tests use portfolio equity fraction and projected savings.
 */

/**
 * Compute deterministic risk score and stress tests.
 *
 * @param {object} profile     { age, retirement_age }
 * @param {object} portfolio   { allocation }
 * @param {object} simulation  { savings_gap, projected_savings_at_retirement }
 * @returns {object}           overall_risk_score, risk_level, stress_test, _inputs
 */
export function computeRiskScore(profile = {}, portfolio = {}, simulation = {}) {
  // ── Equity % ─────────────────────────────────────────────────────────────
  const equityAlloc = (portfolio.allocation || []).find((a) => a.asset === 'Equities');
  const equityPct   = equityAlloc ? Number(equityAlloc.percent) : 60;

  // Factor 1: equity concentration (0–3)
  const equityRisk = equityPct >= 75 ? 3 : equityPct >= 55 ? 2 : 1;

  // ── Time horizon ──────────────────────────────────────────────────────────
  const age           = Number(profile.age)            || 35;
  const retirementAge = Number(profile.retirement_age) || 65;
  const yearsToRetire = Math.max(0, retirementAge - age);

  // Factor 2: time horizon (0–3) — less time remaining = more risk
  const timeRisk = yearsToRetire <= 5  ? 3
                 : yearsToRetire <= 10 ? 2
                 : yearsToRetire <= 20 ? 1
                 : 0;

  // ── Savings gap ───────────────────────────────────────────────────────────
  const savingsGap = Number(simulation.savings_gap) || 0;

  // Factor 3: savings gap (0–3)
  const gapRisk = savingsGap >= 500_000 ? 3
                : savingsGap >= 100_000 ? 2
                : savingsGap >  0       ? 1
                : 0;

  // ── Weighted score (1–10) ─────────────────────────────────────────────────
  // Weights: equity×2, time×2, gap×3
  // Max raw = 3*2 + 3*2 + 3*3 = 21
  const rawScore = equityRisk * 2 + timeRisk * 2 + gapRisk * 3;
  const maxRaw   = 3 * 2 + 3 * 2 + 3 * 3; // 21
  const score    = Math.round(Math.max(1, Math.min(10, (rawScore / maxRaw) * 10)));

  const riskLevel = score >= 8 ? 'very high'
                  : score >= 6 ? 'high'
                  : score >= 4 ? 'medium'
                  : 'low';

  // ── Stress tests ──────────────────────────────────────────────────────────
  const projectedSavings  = Number(simulation.projected_savings_at_retirement)
                          || Number(profile.savings)
                          || 0;
  const marketCrashImpact = -Math.round(projectedSavings * (equityPct / 100) * 0.20);
  const inflationImpact   = -Math.round(projectedSavings * 0.05);

  return {
    overall_risk_score: score,
    risk_level:         riskLevel,
    stress_test: {
      market_crash_20pct_impact: marketCrashImpact,
      inflation_spike_impact:    inflationImpact,
    },
    // Inputs exposed so the LLM can reference them in factor descriptions
    _inputs: {
      equityPct,
      yearsToRetire,
      savingsGap,
      equityRisk,
      timeRisk,
      gapRisk,
      rawScore,
    },
  };
}
